#!/bin/sh
#
# Tag for git
#
# Search Vivado tree and find files that should be committed to svn
# in order to be able to compile a checked out project
#
# 12-Sep-2016 DFN Original version derived from tag_for_svn
#
#  The directory structure should be as follows:
# 
# <project>/
#           <project>.xpr (Managed by svn)
#           bd/          (This directory contains the block designs in the 
#                         project. Only .bd files in this sub-directory tree
#                         are managed)
#
#           ip/          (This directory contains added IP not included in the
#                         block designs above.  (eg trigger_clks from clocking
#                         wizard.  Only .bd, .xci, .xdc, .veo, .vhdl files
#                         are managed. )
#
#           scripts/     (.tcl  project & bd scripts - All files managed)
#
#           hdl/         (This directory contains board wrapper hdl files and
#                         the like. All files in this sub-directory tree
#                         are managed.)
#
#           constraints/ (All files managed)


STARTPWD=`pwd`

# Add .xpr files from the current directory
echo " "
echo "Adding .xpr files from the current directory..."
git  add *.xpr

# Add any .bd files we find. 
echo " "
echo "Adding .bd and wrapper files"
find ./ -name "*.bd"  -exec git add -v  {} \;
#find ./ -name "*.bxml"  -exec git add -v  {} \;
#find ./ -name "*.bmm"  -exec git add -v  {} \;
find ./ -name "hw_handoff"  -exec git add -v  {} \;
#find ./ -name "*.xci"  -exec git add -v  {} \;

# Add all hdl files we find -- this adds too much
# echo " "
# echo "Adding .bd, .xci, .veo, .v, .vhdl files.."
# find ./ -maxdepth 2 -name "*.bd" -exec git add -v  {} \;
# find ./ -maxdepth 2 -name "*.xci" -exec git add -v  {} \;
# find ./ -maxdepth 2 -name "*.veo" -exec git add -v  {} \;
# find ./ -maxdepth 2 -name "*.v" -exec git add -v  {} \;
# find ./ -maxdepth 2 -name "*.vhdl" -exec git add -v  {} \;

# Add all .tcl  files in the scripts directory
if test -d scripts
then
    echo " "
    echo "Adding .tcl files from the scripts/ subdirectory..."
    cd scripts
    find ./ -name "*.tcl" -exec git add -v  {} \;
    cd $STARTPWD
fi

# Add all .xdc files -- adds far to much
#echo " "
#echo "Adding all .xdc files..." 
#find ./ -name "*.xdc" -exec git add -v  {} \;

# Add .hw files
echo " "
echo "Adding .hw files..."
find ./ -maxdepth 1 -name "*.hw" -type d -exec git add -v {} \;

# Add all sdk files
echo " "
echo "Adding all .sdk files..."
find ./ -name "*.sdk" -type d -exec git add -v {} \;

# Add all srcs files
echo " "
echo "Adding all .srcs files..."
find ./ -name "*.srcs" -type d -exec git add -v {} \;

# Clean up some files that should not have been added
find ./ -name "*.zip" -exec git reset  {} \;
find ./ -name "*.str" -exec git reset  {} \;

echo " "
echo "Finished.  Please check that all desired files have been added"
echo "and that extraneous files have not been added to git.  Some hand"
echo "followup commands may need to be given."

