/* Definition for CPU ID */
#define XPAR_CPU_ID 0

/* Definitions for peripheral PS7_CORTEXA9_0 */
#define XPAR_PS7_CORTEXA9_0_CPU_CLK_FREQ_HZ 333333344


/******************************************************************/

/* Canonical definitions for peripheral PS7_CORTEXA9_0 */
#define XPAR_CPU_CORTEXA9_0_CPU_CLK_FREQ_HZ 333333344


/******************************************************************/

#include "xparameters_ps.h"

#define STDIN_BASEADDRESS 0xE0001000
#define STDOUT_BASEADDRESS 0xE0001000

/******************************************************************/

/* Definitions for driver AXICDMA */
#define XPAR_XAXICDMA_NUM_INSTANCES 1

/* Definitions for peripheral ZYNC_BLOCK_AXI_CDMA_0 */
#define XPAR_ZYNC_BLOCK_AXI_CDMA_0_DEVICE_ID 0
#define XPAR_ZYNC_BLOCK_AXI_CDMA_0_BASEADDR 0x7E200000
#define XPAR_ZYNC_BLOCK_AXI_CDMA_0_HIGHADDR 0x7E20FFFF
#define XPAR_ZYNC_BLOCK_AXI_CDMA_0_INCLUDE_DRE 0
#define XPAR_ZYNC_BLOCK_AXI_CDMA_0_USE_DATAMOVER_LITE 0
#define XPAR_ZYNC_BLOCK_AXI_CDMA_0_M_AXI_DATA_WIDTH 32
#define XPAR_ZYNC_BLOCK_AXI_CDMA_0_INCLUDE_SG 1
#define XPAR_ZYNC_BLOCK_AXI_CDMA_0_M_AXI_MAX_BURST_LEN 16


/******************************************************************/

/* Canonical definitions for peripheral ZYNC_BLOCK_AXI_CDMA_0 */
#define XPAR_AXICDMA_0_DEVICE_ID XPAR_ZYNC_BLOCK_AXI_CDMA_0_DEVICE_ID
#define XPAR_AXICDMA_0_BASEADDR 0x7E200000
#define XPAR_AXICDMA_0_HIGHADDR 0x7E20FFFF
#define XPAR_AXICDMA_0_INCLUDE_DRE 0
#define XPAR_AXICDMA_0_USE_DATAMOVER_LITE 0
#define XPAR_AXICDMA_0_M_AXI_DATA_WIDTH 32
#define XPAR_AXICDMA_0_INCLUDE_SG 1
#define XPAR_AXICDMA_0_M_AXI_MAX_BURST_LEN 16


/******************************************************************/

/* Definitions for driver BRAM */
#define XPAR_XBRAM_NUM_INSTANCES 7

/* Definitions for peripheral TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_0 */
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_0_DEVICE_ID 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_0_DATA_WIDTH 32
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_0_ECC 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_0_FAULT_INJECT 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_0_CE_FAILING_REGISTERS 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_0_UE_FAILING_REGISTERS 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_0_ECC_STATUS_REGISTERS 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_0_CE_COUNTER_WIDTH 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_0_ECC_ONOFF_REGISTER 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_0_ECC_ONOFF_RESET_VALUE 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_0_WRITE_ACCESS 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_0_S_AXI_BASEADDR 0x44000000
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_0_S_AXI_HIGHADDR 0x44007FFF
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_0_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_0_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_1 */
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_1_DEVICE_ID 1
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_1_DATA_WIDTH 32
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_1_ECC 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_1_FAULT_INJECT 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_1_CE_FAILING_REGISTERS 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_1_UE_FAILING_REGISTERS 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_1_ECC_STATUS_REGISTERS 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_1_CE_COUNTER_WIDTH 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_1_ECC_ONOFF_REGISTER 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_1_ECC_ONOFF_RESET_VALUE 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_1_WRITE_ACCESS 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_1_S_AXI_BASEADDR 0x46000000
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_1_S_AXI_HIGHADDR 0x46007FFF
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_1_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_1_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_2 */
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_2_DEVICE_ID 2
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_2_DATA_WIDTH 32
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_2_ECC 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_2_FAULT_INJECT 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_2_CE_FAILING_REGISTERS 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_2_UE_FAILING_REGISTERS 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_2_ECC_STATUS_REGISTERS 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_2_CE_COUNTER_WIDTH 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_2_ECC_ONOFF_REGISTER 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_2_ECC_ONOFF_RESET_VALUE 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_2_WRITE_ACCESS 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_2_S_AXI_BASEADDR 0x48000000
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_2_S_AXI_HIGHADDR 0x48007FFF
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_2_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_2_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_3 */
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_3_DEVICE_ID 3
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_3_DATA_WIDTH 32
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_3_ECC 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_3_FAULT_INJECT 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_3_CE_FAILING_REGISTERS 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_3_UE_FAILING_REGISTERS 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_3_ECC_STATUS_REGISTERS 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_3_CE_COUNTER_WIDTH 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_3_ECC_ONOFF_REGISTER 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_3_ECC_ONOFF_RESET_VALUE 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_3_WRITE_ACCESS 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_3_S_AXI_BASEADDR 0x4A000000
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_3_S_AXI_HIGHADDR 0x4A007FFF
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_3_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_3_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_4 */
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_4_DEVICE_ID 4
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_4_DATA_WIDTH 32
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_4_ECC 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_4_FAULT_INJECT 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_4_CE_FAILING_REGISTERS 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_4_UE_FAILING_REGISTERS 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_4_ECC_STATUS_REGISTERS 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_4_CE_COUNTER_WIDTH 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_4_ECC_ONOFF_REGISTER 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_4_ECC_ONOFF_RESET_VALUE 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_4_WRITE_ACCESS 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_4_S_AXI_BASEADDR 0x4C000000
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_4_S_AXI_HIGHADDR 0x4C007FFF
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_4_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_4_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_0 */
#define XPAR_TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_0_DEVICE_ID 5
#define XPAR_TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_0_DATA_WIDTH 32
#define XPAR_TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_0_ECC 0
#define XPAR_TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_0_FAULT_INJECT 0
#define XPAR_TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_0_CE_FAILING_REGISTERS 0
#define XPAR_TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_0_UE_FAILING_REGISTERS 0
#define XPAR_TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_0_ECC_STATUS_REGISTERS 0
#define XPAR_TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_0_CE_COUNTER_WIDTH 0
#define XPAR_TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_0_ECC_ONOFF_REGISTER 0
#define XPAR_TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_0_ECC_ONOFF_RESET_VALUE 0
#define XPAR_TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_0_WRITE_ACCESS 0
#define XPAR_TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_0_S_AXI_BASEADDR 0x40000000
#define XPAR_TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_0_S_AXI_HIGHADDR 0x4001FFFF
#define XPAR_TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_0_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_0_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_1 */
#define XPAR_TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_1_DEVICE_ID 6
#define XPAR_TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_1_DATA_WIDTH 32
#define XPAR_TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_1_ECC 0
#define XPAR_TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_1_FAULT_INJECT 0
#define XPAR_TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_1_CE_FAILING_REGISTERS 0
#define XPAR_TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_1_UE_FAILING_REGISTERS 0
#define XPAR_TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_1_ECC_STATUS_REGISTERS 0
#define XPAR_TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_1_CE_COUNTER_WIDTH 0
#define XPAR_TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_1_ECC_ONOFF_REGISTER 0
#define XPAR_TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_1_ECC_ONOFF_RESET_VALUE 0
#define XPAR_TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_1_WRITE_ACCESS 0
#define XPAR_TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_1_S_AXI_BASEADDR 0x42000000
#define XPAR_TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_1_S_AXI_HIGHADDR 0x4201FFFF
#define XPAR_TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_1_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_1_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/******************************************************************/

/* Canonical definitions for peripheral TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_0 */
#define XPAR_BRAM_0_DEVICE_ID XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_0_DEVICE_ID
#define XPAR_BRAM_0_DATA_WIDTH 32
#define XPAR_BRAM_0_ECC 0
#define XPAR_BRAM_0_FAULT_INJECT 0
#define XPAR_BRAM_0_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_0_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_0_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_0_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_0_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_0_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_0_WRITE_ACCESS 0
#define XPAR_BRAM_0_BASEADDR 0x44000000
#define XPAR_BRAM_0_HIGHADDR 0x44007FFF

/* Canonical definitions for peripheral TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_1 */
#define XPAR_BRAM_1_DEVICE_ID XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_1_DEVICE_ID
#define XPAR_BRAM_1_DATA_WIDTH 32
#define XPAR_BRAM_1_ECC 0
#define XPAR_BRAM_1_FAULT_INJECT 0
#define XPAR_BRAM_1_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_1_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_1_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_1_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_1_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_1_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_1_WRITE_ACCESS 0
#define XPAR_BRAM_1_BASEADDR 0x46000000
#define XPAR_BRAM_1_HIGHADDR 0x46007FFF

/* Canonical definitions for peripheral TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_2 */
#define XPAR_BRAM_2_DEVICE_ID XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_2_DEVICE_ID
#define XPAR_BRAM_2_DATA_WIDTH 32
#define XPAR_BRAM_2_ECC 0
#define XPAR_BRAM_2_FAULT_INJECT 0
#define XPAR_BRAM_2_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_2_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_2_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_2_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_2_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_2_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_2_WRITE_ACCESS 0
#define XPAR_BRAM_2_BASEADDR 0x48000000
#define XPAR_BRAM_2_HIGHADDR 0x48007FFF

/* Canonical definitions for peripheral TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_3 */
#define XPAR_BRAM_3_DEVICE_ID XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_3_DEVICE_ID
#define XPAR_BRAM_3_DATA_WIDTH 32
#define XPAR_BRAM_3_ECC 0
#define XPAR_BRAM_3_FAULT_INJECT 0
#define XPAR_BRAM_3_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_3_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_3_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_3_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_3_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_3_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_3_WRITE_ACCESS 0
#define XPAR_BRAM_3_BASEADDR 0x4A000000
#define XPAR_BRAM_3_HIGHADDR 0x4A007FFF

/* Canonical definitions for peripheral TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_4 */
#define XPAR_BRAM_4_DEVICE_ID XPAR_TRIGGER_MEMORY_BLOCK_SHOWER_MEMORY_BLOCK_AXI_BRAM_CTRL_4_DEVICE_ID
#define XPAR_BRAM_4_DATA_WIDTH 32
#define XPAR_BRAM_4_ECC 0
#define XPAR_BRAM_4_FAULT_INJECT 0
#define XPAR_BRAM_4_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_4_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_4_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_4_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_4_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_4_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_4_WRITE_ACCESS 0
#define XPAR_BRAM_4_BASEADDR 0x4C000000
#define XPAR_BRAM_4_HIGHADDR 0x4C007FFF

/* Canonical definitions for peripheral TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_0 */
#define XPAR_BRAM_5_DEVICE_ID XPAR_TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_0_DEVICE_ID
#define XPAR_BRAM_5_DATA_WIDTH 32
#define XPAR_BRAM_5_ECC 0
#define XPAR_BRAM_5_FAULT_INJECT 0
#define XPAR_BRAM_5_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_5_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_5_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_5_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_5_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_5_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_5_WRITE_ACCESS 0
#define XPAR_BRAM_5_BASEADDR 0x40000000
#define XPAR_BRAM_5_HIGHADDR 0x4001FFFF

/* Canonical definitions for peripheral TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_1 */
#define XPAR_BRAM_6_DEVICE_ID XPAR_TRIGGER_MEMORY_BLOCK_MUON_MEMORY_BLOCK_AXI_BRAM_CTRL_1_DEVICE_ID
#define XPAR_BRAM_6_DATA_WIDTH 32
#define XPAR_BRAM_6_ECC 0
#define XPAR_BRAM_6_FAULT_INJECT 0
#define XPAR_BRAM_6_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_6_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_6_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_6_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_6_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_6_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_6_WRITE_ACCESS 0
#define XPAR_BRAM_6_BASEADDR 0x42000000
#define XPAR_BRAM_6_HIGHADDR 0x4201FFFF


/******************************************************************/

/* Definitions for driver DEVCFG */
#define XPAR_XDCFG_NUM_INSTANCES 1

/* Definitions for peripheral PS7_DEV_CFG_0 */
#define XPAR_PS7_DEV_CFG_0_DEVICE_ID 0
#define XPAR_PS7_DEV_CFG_0_BASEADDR 0xF8007000
#define XPAR_PS7_DEV_CFG_0_HIGHADDR 0xF80070FF


/******************************************************************/

/* Canonical definitions for peripheral PS7_DEV_CFG_0 */
#define XPAR_XDCFG_0_DEVICE_ID XPAR_PS7_DEV_CFG_0_DEVICE_ID
#define XPAR_XDCFG_0_BASEADDR 0xF8007000
#define XPAR_XDCFG_0_HIGHADDR 0xF80070FF


/******************************************************************/

/* Definitions for driver DMAPS */
#define XPAR_XDMAPS_NUM_INSTANCES 2

/* Definitions for peripheral PS7_DMA_NS */
#define XPAR_PS7_DMA_NS_DEVICE_ID 0
#define XPAR_PS7_DMA_NS_BASEADDR 0xF8004000
#define XPAR_PS7_DMA_NS_HIGHADDR 0xF8004FFF


/* Definitions for peripheral PS7_DMA_S */
#define XPAR_PS7_DMA_S_DEVICE_ID 1
#define XPAR_PS7_DMA_S_BASEADDR 0xF8003000
#define XPAR_PS7_DMA_S_HIGHADDR 0xF8003FFF


/******************************************************************/

/* Canonical definitions for peripheral PS7_DMA_NS */
#define XPAR_XDMAPS_0_DEVICE_ID XPAR_PS7_DMA_NS_DEVICE_ID
#define XPAR_XDMAPS_0_BASEADDR 0xF8004000
#define XPAR_XDMAPS_0_HIGHADDR 0xF8004FFF

/* Canonical definitions for peripheral PS7_DMA_S */
#define XPAR_XDMAPS_1_DEVICE_ID XPAR_PS7_DMA_S_DEVICE_ID
#define XPAR_XDMAPS_1_BASEADDR 0xF8003000
#define XPAR_XDMAPS_1_HIGHADDR 0xF8003FFF


/******************************************************************/

/* Definitions for driver EMACPS */
#define XPAR_XEMACPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_ETHERNET_0 */
#define XPAR_PS7_ETHERNET_0_DEVICE_ID 0
#define XPAR_PS7_ETHERNET_0_BASEADDR 0xE000B000
#define XPAR_PS7_ETHERNET_0_HIGHADDR 0xE000BFFF
#define XPAR_PS7_ETHERNET_0_ENET_CLK_FREQ_HZ 125000000
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_1000MBPS_DIV0 10
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_1000MBPS_DIV1 1
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_100MBPS_DIV0 10
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_100MBPS_DIV1 5
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_10MBPS_DIV0 10
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_10MBPS_DIV1 50


/******************************************************************/

/* Canonical definitions for peripheral PS7_ETHERNET_0 */
#define XPAR_XEMACPS_0_DEVICE_ID XPAR_PS7_ETHERNET_0_DEVICE_ID
#define XPAR_XEMACPS_0_BASEADDR 0xE000B000
#define XPAR_XEMACPS_0_HIGHADDR 0xE000BFFF
#define XPAR_XEMACPS_0_ENET_CLK_FREQ_HZ 125000000
#define XPAR_XEMACPS_0_ENET_SLCR_1000Mbps_DIV0 10
#define XPAR_XEMACPS_0_ENET_SLCR_1000Mbps_DIV1 1
#define XPAR_XEMACPS_0_ENET_SLCR_100Mbps_DIV0 10
#define XPAR_XEMACPS_0_ENET_SLCR_100Mbps_DIV1 5
#define XPAR_XEMACPS_0_ENET_SLCR_10Mbps_DIV0 10
#define XPAR_XEMACPS_0_ENET_SLCR_10Mbps_DIV1 50


/******************************************************************/


/* Definitions for peripheral PS7_AFI_0 */
#define XPAR_PS7_AFI_0_S_AXI_BASEADDR 0xF8008000
#define XPAR_PS7_AFI_0_S_AXI_HIGHADDR 0xF8008FFF


/* Definitions for peripheral PS7_AFI_1 */
#define XPAR_PS7_AFI_1_S_AXI_BASEADDR 0xF8009000
#define XPAR_PS7_AFI_1_S_AXI_HIGHADDR 0xF8009FFF


/* Definitions for peripheral PS7_AFI_2 */
#define XPAR_PS7_AFI_2_S_AXI_BASEADDR 0xF800A000
#define XPAR_PS7_AFI_2_S_AXI_HIGHADDR 0xF800AFFF


/* Definitions for peripheral PS7_AFI_3 */
#define XPAR_PS7_AFI_3_S_AXI_BASEADDR 0xF800B000
#define XPAR_PS7_AFI_3_S_AXI_HIGHADDR 0xF800BFFF


/* Definitions for peripheral PS7_DDR_0 */
#define XPAR_PS7_DDR_0_S_AXI_BASEADDR 0x00100000
#define XPAR_PS7_DDR_0_S_AXI_HIGHADDR 0x3FFFFFFF


/* Definitions for peripheral PS7_DDRC_0 */
#define XPAR_PS7_DDRC_0_S_AXI_BASEADDR 0xF8006000
#define XPAR_PS7_DDRC_0_S_AXI_HIGHADDR 0xF8006FFF


/* Definitions for peripheral PS7_GLOBALTIMER_0 */
#define XPAR_PS7_GLOBALTIMER_0_S_AXI_BASEADDR 0xF8F00200
#define XPAR_PS7_GLOBALTIMER_0_S_AXI_HIGHADDR 0xF8F002FF


/* Definitions for peripheral PS7_GPV_0 */
#define XPAR_PS7_GPV_0_S_AXI_BASEADDR 0xF8900000
#define XPAR_PS7_GPV_0_S_AXI_HIGHADDR 0xF89FFFFF


/* Definitions for peripheral PS7_INTC_DIST_0 */
#define XPAR_PS7_INTC_DIST_0_S_AXI_BASEADDR 0xF8F01000
#define XPAR_PS7_INTC_DIST_0_S_AXI_HIGHADDR 0xF8F01FFF


/* Definitions for peripheral PS7_IOP_BUS_CONFIG_0 */
#define XPAR_PS7_IOP_BUS_CONFIG_0_S_AXI_BASEADDR 0xE0200000
#define XPAR_PS7_IOP_BUS_CONFIG_0_S_AXI_HIGHADDR 0xE0200FFF


/* Definitions for peripheral PS7_L2CACHEC_0 */
#define XPAR_PS7_L2CACHEC_0_S_AXI_BASEADDR 0xF8F02000
#define XPAR_PS7_L2CACHEC_0_S_AXI_HIGHADDR 0xF8F02FFF


/* Definitions for peripheral PS7_OCMC_0 */
#define XPAR_PS7_OCMC_0_S_AXI_BASEADDR 0xF800C000
#define XPAR_PS7_OCMC_0_S_AXI_HIGHADDR 0xF800CFFF


/* Definitions for peripheral PS7_PL310_0 */
#define XPAR_PS7_PL310_0_S_AXI_BASEADDR 0xF8F02000
#define XPAR_PS7_PL310_0_S_AXI_HIGHADDR 0xF8F02FFF


/* Definitions for peripheral PS7_PMU_0 */
#define XPAR_PS7_PMU_0_S_AXI_BASEADDR 0xF8891000
#define XPAR_PS7_PMU_0_S_AXI_HIGHADDR 0xF8891FFF
#define XPAR_PS7_PMU_0_PMU1_S_AXI_BASEADDR 0xF8893000
#define XPAR_PS7_PMU_0_PMU1_S_AXI_HIGHADDR 0xF8893FFF


/* Definitions for peripheral PS7_QSPI_LINEAR_0 */
#define XPAR_PS7_QSPI_LINEAR_0_S_AXI_BASEADDR 0xFC000000
#define XPAR_PS7_QSPI_LINEAR_0_S_AXI_HIGHADDR 0xFDFFFFFF


/* Definitions for peripheral PS7_RAM_0 */
#define XPAR_PS7_RAM_0_S_AXI_BASEADDR 0x00000000
#define XPAR_PS7_RAM_0_S_AXI_HIGHADDR 0x0003FFFF


/* Definitions for peripheral PS7_RAM_1 */
#define XPAR_PS7_RAM_1_S_AXI_BASEADDR 0xFFFC0000
#define XPAR_PS7_RAM_1_S_AXI_HIGHADDR 0xFFFFFFFF


/* Definitions for peripheral PS7_SCUC_0 */
#define XPAR_PS7_SCUC_0_S_AXI_BASEADDR 0xF8F00000
#define XPAR_PS7_SCUC_0_S_AXI_HIGHADDR 0xF8F000FC


/* Definitions for peripheral PS7_SLCR_0 */
#define XPAR_PS7_SLCR_0_S_AXI_BASEADDR 0xF8000000
#define XPAR_PS7_SLCR_0_S_AXI_HIGHADDR 0xF8000FFF


/******************************************************************/

/* Definitions for driver GPIOPS */
#define XPAR_XGPIOPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_GPIO_0 */
#define XPAR_PS7_GPIO_0_DEVICE_ID 0
#define XPAR_PS7_GPIO_0_BASEADDR 0xE000A000
#define XPAR_PS7_GPIO_0_HIGHADDR 0xE000AFFF


/******************************************************************/

/* Canonical definitions for peripheral PS7_GPIO_0 */
#define XPAR_XGPIOPS_0_DEVICE_ID XPAR_PS7_GPIO_0_DEVICE_ID
#define XPAR_XGPIOPS_0_BASEADDR 0xE000A000
#define XPAR_XGPIOPS_0_HIGHADDR 0xE000AFFF


/******************************************************************/

/* Definitions for driver IICPS */
#define XPAR_XIICPS_NUM_INSTANCES 2

/* Definitions for peripheral PS7_I2C_0 */
#define XPAR_PS7_I2C_0_DEVICE_ID 0
#define XPAR_PS7_I2C_0_BASEADDR 0xE0004000
#define XPAR_PS7_I2C_0_HIGHADDR 0xE0004FFF
#define XPAR_PS7_I2C_0_I2C_CLK_FREQ_HZ 55555557


/* Definitions for peripheral PS7_I2C_1 */
#define XPAR_PS7_I2C_1_DEVICE_ID 1
#define XPAR_PS7_I2C_1_BASEADDR 0xE0005000
#define XPAR_PS7_I2C_1_HIGHADDR 0xE0005FFF
#define XPAR_PS7_I2C_1_I2C_CLK_FREQ_HZ 55555557


/******************************************************************/

/* Canonical definitions for peripheral PS7_I2C_0 */
#define XPAR_XIICPS_0_DEVICE_ID XPAR_PS7_I2C_0_DEVICE_ID
#define XPAR_XIICPS_0_BASEADDR 0xE0004000
#define XPAR_XIICPS_0_HIGHADDR 0xE0004FFF
#define XPAR_XIICPS_0_I2C_CLK_FREQ_HZ 55555557

/* Canonical definitions for peripheral PS7_I2C_1 */
#define XPAR_XIICPS_1_DEVICE_ID XPAR_PS7_I2C_1_DEVICE_ID
#define XPAR_XIICPS_1_BASEADDR 0xE0005000
#define XPAR_XIICPS_1_HIGHADDR 0xE0005FFF
#define XPAR_XIICPS_1_I2C_CLK_FREQ_HZ 55555557


/******************************************************************/

/* Definitions for driver INTERFACE_UUB_DFN3 */
#define XPAR_INTERFACE_UUB_DFN3_NUM_INSTANCES 1

/* Definitions for peripheral INTERFACE_UUB_DFN3_0 */
#define XPAR_INTERFACE_UUB_DFN3_0_DEVICE_ID 0
#define XPAR_INTERFACE_UUB_DFN3_0_S00_AXI_BASEADDR 0x43C00000
#define XPAR_INTERFACE_UUB_DFN3_0_S00_AXI_HIGHADDR 0x43C0FFFF


/******************************************************************/

/* Definitions for driver QSPIPS */
#define XPAR_XQSPIPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_QSPI_0 */
#define XPAR_PS7_QSPI_0_DEVICE_ID 0
#define XPAR_PS7_QSPI_0_BASEADDR 0xE000D000
#define XPAR_PS7_QSPI_0_HIGHADDR 0xE000DFFF
#define XPAR_PS7_QSPI_0_QSPI_CLK_FREQ_HZ 59523808
#define XPAR_PS7_QSPI_0_QSPI_MODE 1


/******************************************************************/

/* Canonical definitions for peripheral PS7_QSPI_0 */
#define XPAR_XQSPIPS_0_DEVICE_ID XPAR_PS7_QSPI_0_DEVICE_ID
#define XPAR_XQSPIPS_0_BASEADDR 0xE000D000
#define XPAR_XQSPIPS_0_HIGHADDR 0xE000DFFF
#define XPAR_XQSPIPS_0_QSPI_CLK_FREQ_HZ 59523808
#define XPAR_XQSPIPS_0_QSPI_MODE 1


/******************************************************************/


/***Definitions for Core_nIRQ/nFIQ interrupts ****/
/* Definitions for Fabric interrupts connected to ps7_scugic_0 */
#define XPAR_FABRIC_ZYNC_BLOCK_AXI_CDMA_0_CDMA_INTROUT_INTR 61
#define XPAR_FABRIC_TRIGGER_MEMORY_BLOCK_SDE_TRIGGER_0_IRQ_INTR 62

/******************************************************************/

/* Canonical definitions for Fabric interrupts connected to ps7_scugic_0 */

/******************************************************************/

/* Definitions for driver SCUGIC */
#define XPAR_XSCUGIC_NUM_INSTANCES 1

/* Definitions for peripheral PS7_SCUGIC_0 */
#define XPAR_PS7_SCUGIC_0_DEVICE_ID 0
#define XPAR_PS7_SCUGIC_0_BASEADDR 0xF8F00100
#define XPAR_PS7_SCUGIC_0_HIGHADDR 0xF8F001FF
#define XPAR_PS7_SCUGIC_0_DIST_BASEADDR 0xF8F01000


/******************************************************************/

/* Canonical definitions for peripheral PS7_SCUGIC_0 */
#define XPAR_SCUGIC_0_DEVICE_ID 0
#define XPAR_SCUGIC_0_CPU_BASEADDR 0xF8F00100
#define XPAR_SCUGIC_0_CPU_HIGHADDR 0xF8F001FF
#define XPAR_SCUGIC_0_DIST_BASEADDR 0xF8F01000


/******************************************************************/

/* Definitions for driver SCUTIMER */
#define XPAR_XSCUTIMER_NUM_INSTANCES 1

/* Definitions for peripheral PS7_SCUTIMER_0 */
#define XPAR_PS7_SCUTIMER_0_DEVICE_ID 0
#define XPAR_PS7_SCUTIMER_0_BASEADDR 0xF8F00600
#define XPAR_PS7_SCUTIMER_0_HIGHADDR 0xF8F0061F


/******************************************************************/

/* Canonical definitions for peripheral PS7_SCUTIMER_0 */
#define XPAR_XSCUTIMER_0_DEVICE_ID XPAR_PS7_SCUTIMER_0_DEVICE_ID
#define XPAR_XSCUTIMER_0_BASEADDR 0xF8F00600
#define XPAR_XSCUTIMER_0_HIGHADDR 0xF8F0061F


/******************************************************************/

/* Definitions for driver SCUWDT */
#define XPAR_XSCUWDT_NUM_INSTANCES 1

/* Definitions for peripheral PS7_SCUWDT_0 */
#define XPAR_PS7_SCUWDT_0_DEVICE_ID 0
#define XPAR_PS7_SCUWDT_0_BASEADDR 0xF8F00620
#define XPAR_PS7_SCUWDT_0_HIGHADDR 0xF8F006FF


/******************************************************************/

/* Canonical definitions for peripheral PS7_SCUWDT_0 */
#define XPAR_SCUWDT_0_DEVICE_ID XPAR_PS7_SCUWDT_0_DEVICE_ID
#define XPAR_SCUWDT_0_BASEADDR 0xF8F00620
#define XPAR_SCUWDT_0_HIGHADDR 0xF8F006FF


/******************************************************************/

/* Definitions for driver SDE_TRIGGER */
#define XPAR_SDE_TRIGGER_NUM_INSTANCES 1

/* Definitions for peripheral TRIGGER_MEMORY_BLOCK_SDE_TRIGGER_0 */
#define XPAR_TRIGGER_MEMORY_BLOCK_SDE_TRIGGER_0_DEVICE_ID 0
#define XPAR_TRIGGER_MEMORY_BLOCK_SDE_TRIGGER_0_S00_AXI_BASEADDR 0x43C20000
#define XPAR_TRIGGER_MEMORY_BLOCK_SDE_TRIGGER_0_S00_AXI_HIGHADDR 0x43C2FFFF


/******************************************************************/

/* Definitions for driver SPIPS */
#define XPAR_XSPIPS_NUM_INSTANCES 2

/* Definitions for peripheral PS7_SPI_0 */
#define XPAR_PS7_SPI_0_DEVICE_ID 0
#define XPAR_PS7_SPI_0_BASEADDR 0xE0006000
#define XPAR_PS7_SPI_0_HIGHADDR 0xE0006FFF
#define XPAR_PS7_SPI_0_SPI_CLK_FREQ_HZ 96153847


/* Definitions for peripheral PS7_SPI_1 */
#define XPAR_PS7_SPI_1_DEVICE_ID 1
#define XPAR_PS7_SPI_1_BASEADDR 0xE0007000
#define XPAR_PS7_SPI_1_HIGHADDR 0xE0007FFF
#define XPAR_PS7_SPI_1_SPI_CLK_FREQ_HZ 96153847


/******************************************************************/

/* Canonical definitions for peripheral PS7_SPI_0 */
#define XPAR_XSPIPS_0_DEVICE_ID XPAR_PS7_SPI_0_DEVICE_ID
#define XPAR_XSPIPS_0_BASEADDR 0xE0006000
#define XPAR_XSPIPS_0_HIGHADDR 0xE0006FFF
#define XPAR_XSPIPS_0_SPI_CLK_FREQ_HZ 96153847

/* Canonical definitions for peripheral PS7_SPI_1 */
#define XPAR_XSPIPS_1_DEVICE_ID XPAR_PS7_SPI_1_DEVICE_ID
#define XPAR_XSPIPS_1_BASEADDR 0xE0007000
#define XPAR_XSPIPS_1_HIGHADDR 0xE0007FFF
#define XPAR_XSPIPS_1_SPI_CLK_FREQ_HZ 96153847


/******************************************************************/

/* Definitions for driver TIME_TAGGING */
#define XPAR_TIME_TAGGING_NUM_INSTANCES 1

/* Definitions for peripheral TIME_TAGGING_0 */
#define XPAR_TIME_TAGGING_0_DEVICE_ID 0
#define XPAR_TIME_TAGGING_0_S00_AXI_BASEADDR 0x43C30000
#define XPAR_TIME_TAGGING_0_S00_AXI_HIGHADDR 0x43C3FFFF


/******************************************************************/

/* Definitions for driver UARTLITE */
#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_AXI_UARTLITE_0_BASEADDR 0x42C00000
#define XPAR_AXI_UARTLITE_0_HIGHADDR 0x42C0FFFF
#define XPAR_AXI_UARTLITE_0_DEVICE_ID 0
#define XPAR_AXI_UARTLITE_0_BAUDRATE 9600
#define XPAR_AXI_UARTLITE_0_USE_PARITY 0
#define XPAR_AXI_UARTLITE_0_ODD_PARITY 0
#define XPAR_AXI_UARTLITE_0_DATA_BITS 8


/******************************************************************/

/* Canonical definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_UARTLITE_0_DEVICE_ID XPAR_AXI_UARTLITE_0_DEVICE_ID
#define XPAR_UARTLITE_0_BASEADDR 0x42C00000
#define XPAR_UARTLITE_0_HIGHADDR 0x42C0FFFF
#define XPAR_UARTLITE_0_BAUDRATE 9600
#define XPAR_UARTLITE_0_USE_PARITY 0
#define XPAR_UARTLITE_0_ODD_PARITY 0
#define XPAR_UARTLITE_0_DATA_BITS 8


/******************************************************************/

/* Definitions for driver UARTPS */
#define XPAR_XUARTPS_NUM_INSTANCES 2

/* Definitions for peripheral PS7_UART_0 */
#define XPAR_PS7_UART_0_DEVICE_ID 0
#define XPAR_PS7_UART_0_BASEADDR 0xE0000000
#define XPAR_PS7_UART_0_HIGHADDR 0xE0000FFF
#define XPAR_PS7_UART_0_UART_CLK_FREQ_HZ 96153847
#define XPAR_PS7_UART_0_HAS_MODEM 1


/* Definitions for peripheral PS7_UART_1 */
#define XPAR_PS7_UART_1_DEVICE_ID 1
#define XPAR_PS7_UART_1_BASEADDR 0xE0001000
#define XPAR_PS7_UART_1_HIGHADDR 0xE0001FFF
#define XPAR_PS7_UART_1_UART_CLK_FREQ_HZ 96153847
#define XPAR_PS7_UART_1_HAS_MODEM 0


/******************************************************************/

/* Canonical definitions for peripheral PS7_UART_0 */
#define XPAR_XUARTPS_0_DEVICE_ID XPAR_PS7_UART_0_DEVICE_ID
#define XPAR_XUARTPS_0_BASEADDR 0xE0000000
#define XPAR_XUARTPS_0_HIGHADDR 0xE0000FFF
#define XPAR_XUARTPS_0_UART_CLK_FREQ_HZ 96153847
#define XPAR_XUARTPS_0_HAS_MODEM 1

/* Canonical definitions for peripheral PS7_UART_1 */
#define XPAR_XUARTPS_1_DEVICE_ID XPAR_PS7_UART_1_DEVICE_ID
#define XPAR_XUARTPS_1_BASEADDR 0xE0001000
#define XPAR_XUARTPS_1_HIGHADDR 0xE0001FFF
#define XPAR_XUARTPS_1_UART_CLK_FREQ_HZ 96153847
#define XPAR_XUARTPS_1_HAS_MODEM 0


/******************************************************************/

/* Definitions for driver USBPS */
#define XPAR_XUSBPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_USB_0 */
#define XPAR_PS7_USB_0_DEVICE_ID 0
#define XPAR_PS7_USB_0_BASEADDR 0xE0002000
#define XPAR_PS7_USB_0_HIGHADDR 0xE0002FFF


/******************************************************************/

/* Canonical definitions for peripheral PS7_USB_0 */
#define XPAR_XUSBPS_0_DEVICE_ID XPAR_PS7_USB_0_DEVICE_ID
#define XPAR_XUSBPS_0_BASEADDR 0xE0002000
#define XPAR_XUSBPS_0_HIGHADDR 0xE0002FFF


/******************************************************************/

/* Definitions for driver XADCPS */
#define XPAR_XADCPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_XADC_0 */
#define XPAR_PS7_XADC_0_DEVICE_ID 0
#define XPAR_PS7_XADC_0_BASEADDR 0xF8007100
#define XPAR_PS7_XADC_0_HIGHADDR 0xF8007120


/******************************************************************/

/* Canonical definitions for peripheral PS7_XADC_0 */
#define XPAR_XADCPS_0_DEVICE_ID XPAR_PS7_XADC_0_DEVICE_ID
#define XPAR_XADCPS_0_BASEADDR 0xF8007100
#define XPAR_XADCPS_0_HIGHADDR 0xF8007120


/******************************************************************/

